Create models course topic article
DiStan92/EDUPlatform pull request #9
Opened 2022-10-13 18:00 UTC by katherinameliuk

2022-10-13 18:08 UTC, DiStan92 commented on .gitignore
> +.env.dev
delete .dev

2022-10-13 18:15 UTC, DiStan92 commented on EDUPlatform/users/models.py
> +        verbose_name_plural = "course"
verbose_name_plural = "courses"

2022-10-13 18:16 UTC, DiStan92 commented on EDUPlatform/users/models.py
> +        verbose_name_plural = "topic"
"topics"

2022-10-13 18:16 UTC, DiStan92 commented on EDUPlatform/users/models.py
> +        verbose_name_plural = "article"
"articles"

2022-10-14 05:26 UTC, nikitapt63 requested changes
One more thing, i think its better to add Course, Topic and Article in testing_system.models)

2022-10-14 05:26 UTC, nikitapt63 commented on EDUPlatform/users/models.py
> +    image = models.TextField()
image cannot be in TextField, use ImageField or FileField

2022-10-14 05:26 UTC, nikitapt63 commented on EDUPlatform/users/models.py
> +    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
why set_null?

2022-10-18 16:17 UTC, nikitapt63 approved these changes

2022-10-18 16:18 UTC, merged